export const GAME_CONFIG = {
  // Energy / Action Points
  MAX_ENERGY: 500,
  ENERGY_REGEN_RATE: 1, // per minute
  ENERGY_REGEN_BONUS_MULTIPLIER: 2, // for new players
  ENERGY_REGEN_BONUS_DURATION_HOURS: 72,

  // AP costs
  AP_COST_MOVE: 1,
  AP_COST_TRADE: 1,
  AP_COST_COMBAT_VOLLEY: 2,
  AP_COST_DEPLOY: 1,

  // Universe
  TOTAL_SECTORS: 5000,
  SECTORS_PER_REGION: 35, // average cluster size
  MAX_ADJACENT_SECTORS: 12,
  SECTOR_TYPE_DISTRIBUTION: {
    standard: 0.85,
    one_way: 0.05,
    protected: 0.05,
    harmony_enforced: 0.05,
  },
  NUM_STAR_MALLS: 8,
  NUM_SEED_PLANETS: 6,
  NUM_OUTPOSTS: 200,
  NUM_STARTING_PLANETS: 300,

  // Economy
  STARTING_CREDITS: 10000,
  OUTPOST_BASE_TREASURY: 50000,
  OUTPOST_TREASURY_INJECTION: 500, // per game tick
  BASE_CYRILLIUM_PRICE: 10,
  BASE_FOOD_PRICE: 25,
  BASE_TECH_PRICE: 50,
  PRICE_ELASTICITY: 0.02, // price change per unit of supply delta

  // Decay
  DECAY_INACTIVE_THRESHOLD_HOURS: 48,
  DECAY_COLONIST_RATE: 0.015, // 1.5% per day
  DECAY_DEFENSE_DRAIN_RATE: 0.01, // 1% energy per tick
  DEPLOYABLE_LIFETIME_DAYS: 7,

  // Combat
  MIN_FLEE_CHANCE: 0.15,
  MULTI_SHIP_FLEE_BONUS: 0.10, // per additional attacker
  RACHE_DAMAGE_MULTIPLIER: 0.5,

  // Game tick interval
  TICK_INTERVAL_MS: 60000, // 60 seconds

  // New player
  STARTER_SHIP_TYPE: 'scout',

  // Missions
  MAX_ACTIVE_MISSIONS: 5,
  MISSION_POOL_SIZE: 6,
  MISSION_POOL_REFRESH_MINUTES: 30,

  // Sector Events
  EVENT_SPAWN_CHANCE_PER_TICK: 0.02,
  MAX_ACTIVE_EVENTS: 50,
  EVENT_DEFAULT_LIFETIME_MINUTES: 120,
  AP_COST_INVESTIGATE: 1,

  // Leaderboards
  LEADERBOARD_TOP_N: 20,
  LEADERBOARD_CACHE_TTL_MS: 300000,
  LEADERBOARD_CATEGORIES: ['credits', 'planets', 'combat', 'explored', 'trade', 'syndicate', 'level'] as readonly string[],

  // Messages
  MAX_MESSAGES_PER_PLAYER: 50,
  MAX_MESSAGE_BODY_LENGTH: 1000,

  // Ship Upgrades
  MAX_UPGRADES_PER_SHIP: 6,
  UPGRADE_DIMINISHING_BASE: 0.8,

  // Leveling / Progression
  MAX_LEVEL: 100,
  XP_COMBAT_DESTROY: 150,
  XP_COMBAT_VOLLEY: 15,
  XP_MISSION_COMPLETE_BASE: 50,
  XP_TRADE_SELL: 5,
  XP_TRADE_BUY: 2,
  XP_EXPLORE_NEW_SECTOR: 10,
  XP_CLAIM_PLANET: 75,
  XP_COLONIZE: 1,
  XP_INVESTIGATE_EVENT: 25,
  LEVEL_UP_MAX_ENERGY_BONUS: 1,
  SHIP_LEVEL_GATES: {
    corvette: 5,
    cruiser: 15,
    battleship: 25,
    stealth: 35,
    colony_ship: 45,
  } as Record<string, number>,

  // Mission Expansion
  MISSION_TIER_LEVELS: { 1: 0, 2: 10, 3: 20, 4: 35, 5: 50 } as Record<number, number>,
  CANTINA_MISSION_CHANCE: 0.25,
  CANTINA_GATE_MISSION_ID: 'b0000000-0000-0000-0000-000000000008',
  CANTINA_TALK_COST: 0,

  // NPCs
  XP_NPC_FIRST_ENCOUNTER: 15,
  NPC_DEFAULT_REPUTATION: 0,
  NPC_MAX_REPUTATION: 100,
  NPC_MIN_REPUTATION: -100,
  NPC_FACTION_REP_SPILLOVER: 0.25,
  NPC_REP_PER_TALK: 1,
  NPC_REP_THRESHOLD_FRIENDLY: 20,
  NPC_REP_THRESHOLD_TRUSTED: 50,

  // Warp Gates
  WARP_GATE_COST_CREDITS: 100000,
  WARP_GATE_COST_TECH: 500,
  WARP_GATE_COST_CYRILLIUM: 200,
  WARP_GATE_MAX_PER_SYNDICATE: 3,
  AP_COST_WARP: 2,

  // Tablets
  TABLET_SLOT_UNLOCK_LEVELS: { 1: 10, 2: 30, 3: 60 } as Record<number, number>,
  TABLET_BASE_STORAGE: 5,
  TABLET_STORAGE_PER_5_LEVELS: 1,
  TABLET_COMBINE_COUNT: 3,
  TABLET_COMBINE_COSTS: {
    common: 500, uncommon: 1500, rare: 5000,
    epic: 15000, legendary: 50000,
  } as Record<string, number>,
  TABLET_EQUIP_COSTS: {
    common: 500, uncommon: 1000, rare: 1500,
    epic: 2000, legendary: 2500, mythic: 3000,
  } as Record<string, number>,
  TABLET_EVENT_DROP_CHANCE: 0.15,
  TABLET_RARITY_WEIGHTS: {
    common: 50, uncommon: 25, rare: 15, epic: 7, legendary: 2.5, mythic: 0.5,
  } as Record<string, number>,

  // Crafting
  CRAFTING_BASE_REFINERY_SLOTS: 1,
  CRAFTING_BONUS_SLOTS_ABOVE_LEVEL: 3,
  CRAFTING_TIER2_PLANET_LEVEL: 1,
  CRAFTING_TIER3_PLANET_LEVEL: 3,
  CRAFTING_TIER4_PLANET_LEVEL: 5,
  CRAFTING_MAX_BATCH_SIZE: 5,
  CRAFTING_UNIQUE_RESOURCE_RATE: 0.5,
  XP_CRAFT_TIER2: 10,
  XP_CRAFT_TIER3: 25,
  XP_CRAFT_TIER4: 50,
  XP_COLLECT_RESOURCES: 5,
} as const;
