import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Only delete expanded missions (b0... UUIDs), preserve original seed and starter missions
  await knex('player_missions')
    .whereIn('template_id', function () {
      this.select('id').from('mission_templates').where('id', 'like', 'b0000000%');
    })
    .del();
  await knex('mission_templates').where('id', 'like', 'b0000000%').del();

  const boardMissions = [
    // --- Tier 1 (3 missions) ---
    {
      id: 'b0000000-0000-0000-0000-000000000001',
      title: "Pathfinder's Journey",
      description: 'Chart 5 new sectors to build your star map.',
      type: 'visit_sector',
      difficulty: 1,
      tier: 1,
      objectives: { sectorsToVisit: 5 },
      reward_credits: 800,
      reward_xp: 50,
      hints: ['Explore unvisited sectors by moving through the galaxy.'],
      sort_order: 1,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000002',
      title: 'First Delivery',
      description: 'Sell 8 units of cyrillium to any outpost.',
      type: 'deliver_cargo',
      difficulty: 1,
      tier: 1,
      objectives: { commodity: 'cyrillium', quantity: 8 },
      reward_credits: 600,
      reward_xp: 40,
      hints: ['Buy cyrillium at a cheap outpost and sell it at another.'],
      sort_order: 2,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000003',
      title: 'Sensor Calibration',
      description: 'Perform 3 sector scans to test your sensor array.',
      type: 'scan_sectors',
      difficulty: 1,
      tier: 1,
      objectives: { scansRequired: 3 },
      reward_credits: 500,
      reward_xp: 30,
      hints: ['Use the scan command while in any sector.'],
      sort_order: 3,
    },

    // --- Tier 2 (5 missions) ---
    {
      id: 'b0000000-0000-0000-0000-000000000004',
      title: 'Outpost Supply Run',
      description: 'Deliver 20 food units to feed the frontier outposts.',
      type: 'deliver_cargo',
      difficulty: 2,
      tier: 2,
      objectives: { commodity: 'food', quantity: 20 },
      reward_credits: 2000,
      reward_xp: 100,
      hints: ['Food is cheap on agricultural worlds. Buy low and sell at any outpost.'],
      sort_order: 10,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000005',
      title: 'Frontier Security',
      description: 'Destroy 2 enemy ships to pacify the spacelanes.',
      type: 'destroy_ship',
      difficulty: 2,
      tier: 2,
      objectives: { shipsToDestroy: 2 },
      reward_credits: 3000,
      reward_xp: 150,
      hints: ['Find other players in unprotected sectors and engage in combat.'],
      sort_order: 11,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000006',
      title: 'Colony Foundation',
      description: 'Deposit 30 colonists on your planets to start building an empire.',
      type: 'colonize_planet',
      difficulty: 2,
      tier: 2,
      objectives: { colonistsToDeposit: 30 },
      reward_credits: 2500,
      reward_xp: 120,
      hints: ['Buy colonists at outposts and deposit them on claimed planets.'],
      sort_order: 12,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000007',
      title: 'Deep Space Survey',
      description: 'Explore 12 sectors in the uncharted regions.',
      type: 'visit_sector',
      difficulty: 2,
      tier: 2,
      objectives: { sectorsToVisit: 12 },
      reward_credits: 2000,
      reward_xp: 100,
      hints: ['Keep moving through new sectors. Check your star chart for unexplored areas.'],
      sort_order: 13,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000008',
      title: "The Bartender's Trust",
      description: 'Trade 100 units of goods to prove your reliability. The cantina bartender is watching.',
      type: 'trade_units',
      difficulty: 2,
      tier: 2,
      objectives: { unitsToTrade: 100 },
      reward_credits: 3500,
      reward_xp: 200,
      hints: ['Buy and sell commodities at outposts. Each unit traded counts toward the goal.'],
      sort_order: 14,
    },

    {
      id: 'b0000000-0000-0000-0000-000000000021',
      title: 'Stellar Census',
      description: 'The Vedic Cartographers Guild requires a comprehensive stellar survey before granting naming authority. Scan 8 sectors to catalog the local star systems.',
      type: 'scan_sectors',
      difficulty: 2,
      tier: 2,
      objectives: { scansRequired: 8 },
      reward_credits: 3000,
      reward_xp: 200,
      hints: ['Use your scanner in different sectors to build the catalog.'],
      sort_order: 15,
    },

    // --- Tier 3 (5 missions) ---
    {
      id: 'b0000000-0000-0000-0000-000000000009',
      title: 'Interstellar Logistics',
      description: 'Deliver 40 tech components to the frontier refineries.',
      type: 'deliver_cargo',
      difficulty: 3,
      tier: 3,
      objectives: { commodity: 'tech', quantity: 40 },
      reward_credits: 5000,
      reward_xp: 250,
      requires_claim_at_mall: true,
      hints: ['Tech is expensive but profitable. Stock up and deliver to any outpost.'],
      sort_order: 20,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000010',
      title: 'Sector Pacification',
      description: 'Destroy 4 enemy ships to establish order.',
      type: 'destroy_ship',
      difficulty: 3,
      tier: 3,
      objectives: { shipsToDestroy: 4 },
      reward_credits: 6000,
      reward_xp: 300,
      hints: ['Hunt targets in contested zones. Upgrade your weapons for an edge.'],
      sort_order: 21,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000011',
      title: 'World Builder',
      description: 'Settle 100 colonists across your worlds.',
      type: 'colonize_planet',
      difficulty: 3,
      tier: 3,
      objectives: { colonistsToDeposit: 100 },
      reward_credits: 5500,
      reward_xp: 280,
      hints: ['Use a ship with large cargo holds for efficient colonist transport.'],
      sort_order: 22,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000012',
      title: 'Galactic Census',
      description: 'Perform 15 deep scans to map the galaxy.',
      type: 'scan_sectors',
      difficulty: 3,
      tier: 3,
      objectives: { scansRequired: 15 },
      reward_credits: 4000,
      reward_xp: 200,
      requires_claim_at_mall: true,
      hints: ['Scan sectors as you travel. Each scan counts toward the total.'],
      sort_order: 23,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000013',
      title: 'Supply Chain Master',
      description: 'Trade 300 units of goods through the trade network.',
      type: 'trade_units',
      difficulty: 3,
      tier: 3,
      objectives: { unitsToTrade: 300 },
      reward_credits: 7000,
      reward_xp: 350,
      prerequisite_mission_id: 'b0000000-0000-0000-0000-000000000009',
      hints: ['Buy and sell in bulk at profitable outposts.'],
      sort_order: 24,
    },

    // --- Tier 4 (4 missions) ---
    {
      id: 'b0000000-0000-0000-0000-000000000014',
      title: 'War Campaign',
      description: 'Destroy 7 enemy ships in your campaign of conquest.',
      type: 'destroy_ship',
      difficulty: 4,
      tier: 4,
      objectives: { shipsToDestroy: 7 },
      reward_credits: 12000,
      reward_xp: 500,
      requires_claim_at_mall: true,
      hints: ['Engage multiple opponents. A battleship or stealth fighter gives you an advantage.'],
      sort_order: 30,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000015',
      title: 'Imperial Expansion',
      description: 'Deposit 300 colonists to grow your planetary empire.',
      type: 'colonize_planet',
      difficulty: 4,
      tier: 4,
      objectives: { colonistsToDeposit: 300 },
      reward_credits: 10000,
      reward_xp: 450,
      prerequisite_mission_id: 'b0000000-0000-0000-0000-000000000011',
      hints: ['Use a colony ship for maximum colonist capacity per trip.'],
      sort_order: 31,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000016',
      title: 'Logistical Mastermind',
      description: 'Deliver 80 cyrillium to fuel the war machine.',
      type: 'deliver_cargo',
      difficulty: 4,
      tier: 4,
      objectives: { commodity: 'cyrillium', quantity: 80 },
      reward_credits: 11000,
      reward_xp: 500,
      prerequisite_mission_id: 'b0000000-0000-0000-0000-000000000013',
      hints: ['Cyrillium is found near asteroid sectors. Buy in bulk.'],
      sort_order: 32,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000017',
      title: 'Deep Recon',
      description: 'Traverse 30 sectors across the galaxy.',
      type: 'visit_sector',
      difficulty: 4,
      tier: 4,
      objectives: { sectorsToVisit: 30 },
      reward_credits: 9000,
      reward_xp: 400,
      hints: ['Chart a course through unexplored regions of the galaxy.'],
      sort_order: 33,
    },

    // --- Tier 5 (3 missions) ---
    {
      id: 'b0000000-0000-0000-0000-000000000018',
      title: 'Galactic Dominator',
      description: 'Destroy 12 enemy ships and assert total dominance.',
      type: 'destroy_ship',
      difficulty: 5,
      tier: 5,
      objectives: { shipsToDestroy: 12 },
      reward_credits: 25000,
      reward_xp: 800,
      requires_claim_at_mall: true,
      prerequisite_mission_id: 'b0000000-0000-0000-0000-000000000014',
      hints: ['The ultimate combat challenge. Upgrade everything before attempting.'],
      sort_order: 40,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000019',
      title: 'Empire Architect',
      description: 'Settle 500 colonists to build a galactic empire.',
      type: 'colonize_planet',
      difficulty: 5,
      tier: 5,
      objectives: { colonistsToDeposit: 500 },
      reward_credits: 22000,
      reward_xp: 700,
      prerequisite_mission_id: 'b0000000-0000-0000-0000-000000000015',
      hints: ['Own multiple planets and run colonist shuttle routes.'],
      sort_order: 41,
    },
    {
      id: 'b0000000-0000-0000-0000-000000000020',
      title: 'Omniscient',
      description: 'Complete 40 comprehensive sensor sweeps to achieve mastery.',
      type: 'scan_sectors',
      difficulty: 5,
      tier: 5,
      objectives: { scansRequired: 40 },
      reward_credits: 18000,
      reward_xp: 600,
      hints: ['Scan everywhere you go. Persistence is key.'],
      sort_order: 42,
    },
  ];

  const cantinaMissions = [
    // --- Tier 2-3 cantina missions (6) ---
    {
      id: 'b0000000-0000-0000-0000-0000000000c1',
      title: "Smuggler's Run",
      description: 'The bartender needs 15 tech components moved quietly. No questions asked.',
      type: 'deliver_cargo',
      difficulty: 2,
      tier: 2,
      objectives: { commodity: 'tech', quantity: 15 },
      reward_credits: 3500,
      reward_xp: 180,
      hints: ['Acquire tech discreetly and sell at any outpost.'],
      sort_order: 50,
    },
    {
      id: 'b0000000-0000-0000-0000-0000000000c2',
      title: 'Whiskey Run',
      description: 'The cantina is running low. Deliver 25 food units for the distillery.',
      type: 'deliver_cargo',
      difficulty: 2,
      tier: 2,
      objectives: { commodity: 'food', quantity: 25 },
      reward_credits: 4000,
      reward_xp: 200,
      hints: ['Agricultural outposts sell food cheaply.'],
      sort_order: 51,
    },
    {
      id: 'b0000000-0000-0000-0000-0000000000c3',
      title: 'Shadow Recon',
      description: 'The bartender scrawled coordinates on a napkin. Visit 10 sectors and report back.',
      type: 'visit_sector',
      difficulty: 3,
      tier: 3,
      objectives: { sectorsToVisit: 10 },
      reward_credits: 3000,
      reward_xp: 150,
      hints: ['The bartender scrawled coordinates on a napkin. Explore unknown sectors.'],
      sort_order: 52,
    },
    {
      id: 'b0000000-0000-0000-0000-0000000000c4',
      title: 'Bar Tab Collector',
      description: 'Some regulars owe the bartender. Trade 150 units to cover their debts.',
      type: 'trade_units',
      difficulty: 3,
      tier: 3,
      objectives: { unitsToTrade: 150 },
      reward_credits: 5000,
      reward_xp: 250,
      hints: ['Trade any commodities at any outpost. Volume is what matters.'],
      sort_order: 53,
    },
    {
      id: 'b0000000-0000-0000-0000-0000000000c5',
      title: 'Dirty Work',
      description: 'Someone at the cantina wants 3 pilots removed. Permanently.',
      type: 'destroy_ship',
      difficulty: 3,
      tier: 3,
      objectives: { shipsToDestroy: 3 },
      reward_credits: 5500,
      reward_xp: 280,
      hints: ['Find and destroy enemy ships. The client does not care who.'],
      sort_order: 54,
    },
    {
      id: 'b0000000-0000-0000-0000-0000000000c6',
      title: 'Underground Surveyor',
      description: 'Scan 10 sectors for the bartender\'s mysterious employer.',
      type: 'scan_sectors',
      difficulty: 3,
      tier: 3,
      objectives: { scansRequired: 10 },
      reward_credits: 4500,
      reward_xp: 220,
      hints: ['Use scan in multiple sectors. The employer wants data, not specifics.'],
      sort_order: 55,
    },

    // --- Tier 4-5 cantina missions (4) ---
    {
      id: 'b0000000-0000-0000-0000-0000000000c7',
      title: 'The Big Score',
      description: 'A massive cyrillium shipment needs to disappear. Deliver 60 units with no trail.',
      type: 'deliver_cargo',
      difficulty: 4,
      tier: 4,
      objectives: { commodity: 'cyrillium', quantity: 60 },
      reward_credits: 15000,
      reward_xp: 600,
      requires_claim_at_mall: true,
      hints: ['Buy cyrillium in bulk from remote outposts. Return to any Star Mall to collect payment.'],
      sort_order: 60,
    },
    {
      id: 'b0000000-0000-0000-0000-0000000000c8',
      title: 'Underworld Enforcer',
      description: 'The syndicate wants 8 ships destroyed as a message to their rivals.',
      type: 'destroy_ship',
      difficulty: 4,
      tier: 4,
      objectives: { shipsToDestroy: 8 },
      reward_credits: 18000,
      reward_xp: 700,
      hints: ['A well-armed battleship or stealth fighter is recommended for this job.'],
      sort_order: 61,
    },
    {
      id: 'b0000000-0000-0000-0000-0000000000c9',
      title: "Kingpin's Network",
      description: 'Establish a trade network moving 500 units. The kingpin will be pleased.',
      type: 'trade_units',
      difficulty: 5,
      tier: 5,
      objectives: { unitsToTrade: 500 },
      reward_credits: 20000,
      reward_xp: 750,
      requires_claim_at_mall: true,
      hints: ['Trade at high-volume outposts. The kingpin demands results, not excuses.'],
      sort_order: 62,
    },
    {
      id: 'b0000000-0000-0000-0000-00000000c010',
      title: 'Ghost Protocol',
      description: 'Traverse 35 sectors undetected. The bartender will know if you succeed.',
      type: 'visit_sector',
      difficulty: 5,
      tier: 5,
      objectives: { sectorsToVisit: 35 },
      reward_credits: 16000,
      reward_xp: 650,
      hints: ['Chart a course through remote, less-traveled sectors.'],
      sort_order: 63,
    },
  ];

  for (const t of boardMissions) {
    await knex('mission_templates').insert({
      id: t.id,
      title: t.title,
      description: t.description,
      type: t.type,
      difficulty: t.difficulty,
      tier: t.tier,
      objectives: JSON.stringify(t.objectives),
      reward_credits: t.reward_credits,
      reward_xp: t.reward_xp,
      reward_item_id: null,
      time_limit_minutes: null,
      min_player_level: 0,
      repeatable: false,
      source: 'board',
      requires_claim_at_mall: (t as any).requires_claim_at_mall || false,
      prerequisite_mission_id: (t as any).prerequisite_mission_id || null,
      reward_items: null,
      hints: JSON.stringify(t.hints),
      sort_order: t.sort_order,
    });
  }

  for (const t of cantinaMissions) {
    await knex('mission_templates').insert({
      id: t.id,
      title: t.title,
      description: t.description,
      type: t.type,
      difficulty: t.difficulty,
      tier: t.tier,
      objectives: JSON.stringify(t.objectives),
      reward_credits: t.reward_credits,
      reward_xp: t.reward_xp,
      reward_item_id: null,
      time_limit_minutes: null,
      min_player_level: 0,
      repeatable: false,
      source: 'cantina',
      requires_claim_at_mall: (t as any).requires_claim_at_mall || false,
      prerequisite_mission_id: null,
      reward_items: null,
      hints: JSON.stringify(t.hints),
      sort_order: t.sort_order,
    });
  }
}
